# Generated by Django 4.1 on 2022-09-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('dataNascimento', models.DateField(max_length=100)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.perfil')),
            ],
        ),
    ]
